//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRiaServices.DomainServices.Client.Services {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRiaServices.DomainServices.Client.Linq.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Bitwise operators are not supported in queries. 的本地化字符串。
        /// </summary>
        internal static string QuerySerialization_BitwiseOperatorsNotSupported {
            get {
                return ResourceManager.GetString("QuerySerialization_BitwiseOperatorsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method &apos;{0}&apos; on type &apos;{1}&apos; is not accessible. Only methods on primitive types, System.Math and System.Convert are supported in queries. 的本地化字符串。
        /// </summary>
        internal static string QuerySerialization_MethodNotAccessible {
            get {
                return ResourceManager.GetString("QuerySerialization_MethodNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nested query expressions are not supported. 的本地化字符串。
        /// </summary>
        internal static string QuerySerialization_NestedQueriesNotSupported {
            get {
                return ResourceManager.GetString("QuerySerialization_NestedQueriesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;New&apos; Expressions are not supported in queries. 的本地化字符串。
        /// </summary>
        internal static string QuerySerialization_NewExpressionsNotSupported {
            get {
                return ResourceManager.GetString("QuerySerialization_NewExpressionsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select projections are not supported. 的本地化字符串。
        /// </summary>
        internal static string QuerySerialization_ProjectionsNotSupported {
            get {
                return ResourceManager.GetString("QuerySerialization_ProjectionsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query operator &apos;{0}&apos; is not supported. 的本地化字符串。
        /// </summary>
        internal static string QuerySerialization_UnsupportedQueryOperator {
            get {
                return ResourceManager.GetString("QuerySerialization_UnsupportedQueryOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value of type &apos;{0}&apos; cannot be serialized as part of the query. &apos;{0}&apos; is not a supported type. 的本地化字符串。
        /// </summary>
        internal static string QuerySerialization_UnsupportedType {
            get {
                return ResourceManager.GetString("QuerySerialization_UnsupportedType", resourceCulture);
            }
        }
    }
}
