//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRiaServices.DomainServices.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRiaServices.DomainServices.Client.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user must be authenticated when the Login finishes successfully..
        /// </summary>
        internal static string ApplicationServices_LoginSuccessRequiresAuthN {
            get {
                return ResourceManager.GetString("ApplicationServices_LoginSuccessRequiresAuthN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} operation does not support cancellation..
        /// </summary>
        internal static string ApplicationServices_OperationCannotCancel {
            get {
                return ResourceManager.GetString("ApplicationServices_OperationCannotCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDefaultUser cannot return a null user..
        /// </summary>
        internal static string ApplicationServices_UserIsNull {
            get {
                return ResourceManager.GetString("ApplicationServices_UserIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserService operation already in progress..
        /// </summary>
        internal static string ApplicationServices_UserServiceIsBusy {
            get {
                return ResourceManager.GetString("ApplicationServices_UserServiceIsBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation has already completed..
        /// </summary>
        internal static string AsyncOperation_AlreadyCompleted {
            get {
                return ResourceManager.GetString("AsyncOperation_AlreadyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation does not support cancellation..
        /// </summary>
        internal static string AsyncOperation_CancelNotSupported {
            get {
                return ResourceManager.GetString("AsyncOperation_CancelNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity type &apos;{0}&apos; is abstract and cannot be instantiated..
        /// </summary>
        internal static string Cannot_Create_Abstract_Entity {
            get {
                return ResourceManager.GetString("Cannot_Create_Abstract_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method can only be invoked once..
        /// </summary>
        internal static string MethodCanOnlyBeInvokedOnce {
            get {
                return ResourceManager.GetString("MethodCanOnlyBeInvokedOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntitySet and EntityCollection are already observable and should be bound to directly..
        /// </summary>
        internal static string NoESorEC {
            get {
                return ResourceManager.GetString("NoESorEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was canceled..
        /// </summary>
        internal static string OperationCancelled {
            get {
                return ResourceManager.GetString("OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation has not completed..
        /// </summary>
        internal static string OperationNotComplete {
            get {
                return ResourceManager.GetString("OperationNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitwise operators are not supported in queries..
        /// </summary>
        internal static string QuerySerialization_BitwiseOperatorsNotSupported {
            get {
                return ResourceManager.GetString("QuerySerialization_BitwiseOperatorsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; on type &apos;{1}&apos; is not accessible. Only methods on primitive types, System.Math and System.Convert are supported in queries..
        /// </summary>
        internal static string QuerySerialization_MethodNotAccessible {
            get {
                return ResourceManager.GetString("QuerySerialization_MethodNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nested query expressions are not supported..
        /// </summary>
        internal static string QuerySerialization_NestedQueriesNotSupported {
            get {
                return ResourceManager.GetString("QuerySerialization_NestedQueriesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;New&apos; expressions are not supported in queries..
        /// </summary>
        internal static string QuerySerialization_NewExpressionsNotSupported {
            get {
                return ResourceManager.GetString("QuerySerialization_NewExpressionsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select projections are not supported..
        /// </summary>
        internal static string QuerySerialization_ProjectionsNotSupported {
            get {
                return ResourceManager.GetString("QuerySerialization_ProjectionsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary operation &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string QuerySerialization_UnsupportedBinaryOp {
            get {
                return ResourceManager.GetString("QuerySerialization_UnsupportedBinaryOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query operator &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string QuerySerialization_UnsupportedQueryOperator {
            get {
                return ResourceManager.GetString("QuerySerialization_UnsupportedQueryOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of type &apos;{0}&apos; cannot be serialized as part of the query. &apos;{0}&apos; is not a supported type..
        /// </summary>
        internal static string QuerySerialization_UnsupportedType {
            get {
                return ResourceManager.GetString("QuerySerialization_UnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unary operation &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string QuerySerialization_UnsupportedUnaryOp {
            get {
                return ResourceManager.GetString("QuerySerialization_UnsupportedUnaryOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IAsyncResult object did not come from the corresponding async method on this type..
        /// </summary>
        internal static string WrongAsyncResult {
            get {
                return ResourceManager.GetString("WrongAsyncResult", resourceCulture);
            }
        }
    }
}
