//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRiaServices.DomainServices.Client {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRiaServices.DomainServices.Client.Data.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ComplexObject instances cannot be shared. 的本地化字符串。
        /// </summary>
        internal static string ComplexType_InstancesCannotBeShared {
            get {
                return ResourceManager.GetString("ComplexType_InstancesCannotBeShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reference cycle detected. Entity or ComplexObject members cannot contain cyclic references. 的本地化字符串。
        /// </summary>
        internal static string CyclicReferenceError {
            get {
                return ResourceManager.GetString("CyclicReferenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The DomainClient &apos;{0}&apos; does not support cancellation. 的本地化字符串。
        /// </summary>
        internal static string DomainClient_CancellationNotSupported {
            get {
                return ResourceManager.GetString("DomainClient_CancellationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The submitted change-set was empty. 的本地化字符串。
        /// </summary>
        internal static string DomainClient_EmptyChangeSet {
            get {
                return ResourceManager.GetString("DomainClient_EmptyChangeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EntityTypes has already been initialized 的本地化字符串。
        /// </summary>
        internal static string DomainClient_EntityTypesAlreadyInitialized {
            get {
                return ResourceManager.GetString("DomainClient_EntityTypesAlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom method invocation name cannot be null or empty. 的本地化字符串。
        /// </summary>
        internal static string DomainClient_InvocationNameCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("DomainClient_InvocationNameCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Faild to construct generic WebDomainClient 的本地化字符串。
        /// </summary>
        internal static string DomainClientFactory_FaildToGetGenericDomainClient {
            get {
                return ResourceManager.GetString("DomainClientFactory_FaildToGetGenericDomainClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must reference the assembly &apos;OpenRiaServices.DomainServices.Client.Web&apos; 的本地化字符串。
        /// </summary>
        internal static string DomainClientFactory_MissingClientWebReference {
            get {
                return ResourceManager.GetString("DomainClientFactory_MissingClientWebReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service contract must be an interface 的本地化字符串。
        /// </summary>
        internal static string DomainClientFactory_ServiceContractMustBeAnInterface {
            get {
                return ResourceManager.GetString("DomainClientFactory_ServiceContractMustBeAnInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The EntityContainer for a DomainContext cannot be null. 的本地化字符串。
        /// </summary>
        internal static string DomainContext_EntityContainerCannotBeNull {
            get {
                return ResourceManager.GetString("DomainContext_EntityContainerCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified EntityQuery &apos;{0}&apos; cannot be loaded because it was not created by this DomainContext. 的本地化字符串。
        /// </summary>
        internal static string DomainContext_InvalidEntityQueryDomainClient {
            get {
                return ResourceManager.GetString("DomainContext_InvalidEntityQueryDomainClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified service URI is not correctly formatted. 的本地化字符串。
        /// </summary>
        internal static string DomainContext_InvalidServiceUri {
            get {
                return ResourceManager.GetString("DomainContext_InvalidServiceUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invoke operation &apos;{0}&apos; failed. {1} 的本地化字符串。
        /// </summary>
        internal static string DomainContext_InvokeOperationFailed {
            get {
                return ResourceManager.GetString("DomainContext_InvokeOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invoke operation &apos;{0}&apos; failed validation.  Please inspect ValidationErrors on the operation for details. 的本地化字符串。
        /// </summary>
        internal static string DomainContext_InvokeOperationFailed_Validation {
            get {
                return ResourceManager.GetString("DomainContext_InvokeOperationFailed_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load operation failed for query &apos;{0}&apos;. {1} 的本地化字符串。
        /// </summary>
        internal static string DomainContext_LoadOperationFailed {
            get {
                return ResourceManager.GetString("DomainContext_LoadOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load operation for query &apos;{0}&apos; failed validation.  Please inspect ValidationErrors on the operation for details. 的本地化字符串。
        /// </summary>
        internal static string DomainContext_LoadOperationFailed_Validation {
            get {
                return ResourceManager.GetString("DomainContext_LoadOperationFailed_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The custom update method &apos;{0}&apos; called on entity &apos;{1}&apos; was called through the &apos;{2}&apos; DomainContext, which is not the correct DomainContext. The method may be available through another DomainContext. 的本地化字符串。
        /// </summary>
        internal static string DomainContext_NamedUpdateMethodDoesNotExist {
            get {
                return ResourceManager.GetString("DomainContext_NamedUpdateMethodDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A SubmitChanges operation is already in progress on this DomainContext. 的本地化字符串。
        /// </summary>
        internal static string DomainContext_SubmitAlreadyInProgress {
            get {
                return ResourceManager.GetString("DomainContext_SubmitAlreadyInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit operation failed. {0} 的本地化字符串。
        /// </summary>
        internal static string DomainContext_SubmitOperationFailed {
            get {
                return ResourceManager.GetString("DomainContext_SubmitOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit operation failed due to conflicts. Please inspect Entity.EntityConflict for each entity in EntitiesInError for more information. 的本地化字符串。
        /// </summary>
        internal static string DomainContext_SubmitOperationFailed_Conflicts {
            get {
                return ResourceManager.GetString("DomainContext_SubmitOperationFailed_Conflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit operation failed validation. Please inspect Entity.ValidationErrors for each entity in EntitiesInError for more information. 的本地化字符串。
        /// </summary>
        internal static string DomainContext_SubmitOperationFailed_Validation {
            get {
                return ResourceManager.GetString("DomainContext_SubmitOperationFailed_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Composed child entity &apos;{0}&apos; cannot be assigned to a new parent. 的本地化字符串。
        /// </summary>
        internal static string Entity_CantReparentComposedChild {
            get {
                return ResourceManager.GetString("Entity_CantReparentComposedChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A compositional association on an entity cannot contain the entity itself. 的本地化字符串。
        /// </summary>
        internal static string Entity_ChildCannotBeItsParent {
            get {
                return ResourceManager.GetString("Entity_ChildCannotBeItsParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A custom method cannot be invoked on an entity in a Deleted EntityState. 的本地化字符串。
        /// </summary>
        internal static string Entity_InvokeOnDeletedEntity {
            get {
                return ResourceManager.GetString("Entity_InvokeOnDeletedEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A custom method cannot be invoked on a Detached entity. 的本地化字符串。
        /// </summary>
        internal static string Entity_InvokeOnDetachedEntity {
            get {
                return ResourceManager.GetString("Entity_InvokeOnDetachedEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A custom method cannot be invoked on an entity that is part of a change-set that is in the process of being submitted. 的本地化字符串。
        /// </summary>
        internal static string Entity_InvokeWhileSubmitting {
            get {
                return ResourceManager.GetString("Entity_InvokeWhileSubmitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value of key member &apos;{0}&apos; on an instance of an entity of type &apos;{1}&apos; has changed. Entity key members cannot be changed. 的本地化字符串。
        /// </summary>
        internal static string Entity_KeyMembersCannotBeChanged {
            get {
                return ResourceManager.GetString("Entity_KeyMembersCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only one pending custom method invocation is allowed per entity. 的本地化字符串。
        /// </summary>
        internal static string Entity_MultipleCustomMethodInvocations {
            get {
                return ResourceManager.GetString("Entity_MultipleCustomMethodInvocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find any entity action named &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string Entity_NoEntityActionWithName {
            get {
                return ResourceManager.GetString("Entity_NoEntityActionWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified entity is not a member of this collection 的本地化字符串。
        /// </summary>
        internal static string Entity_Not_In_Collection {
            get {
                return ResourceManager.GetString("Entity_Not_In_Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The property &apos;{0}&apos; on entity type &apos;{1}&apos; is not a change tracked data member. 的本地化字符串。
        /// </summary>
        internal static string Entity_Property_NotChangeTracked {
            get {
                return ResourceManager.GetString("Entity_Property_NotChangeTracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This entity is currently read-only. One of the following conditions exist: a custom method has been invoked, a submit operation is in progress, or edit operations are not supported for the entity type. 的本地化字符串。
        /// </summary>
        internal static string Entity_ReadOnly {
            get {
                return ResourceManager.GetString("Entity_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entity &apos;{0}&apos; is currently being edited and has uncommitted changes. A call to BeginEdit must be followed by a call to EndEdit or CancelEdit before changes can be submitted. 的本地化字符串。
        /// </summary>
        internal static string Entity_UncommittedChanges {
            get {
                return ResourceManager.GetString("Entity_UncommittedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can only undo currently invoked actions 的本地化字符串。
        /// </summary>
        internal static string Entity_UndoInvokeOnlyForInvokedActions {
            get {
                return ResourceManager.GetString("Entity_UndoInvokeOnlyForInvokedActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A custom method cannot be undone on an entity that is part of a change-set that is in the process of being submitted. 的本地化字符串。
        /// </summary>
        internal static string Entity_UndoInvokeWhileSubmitting {
            get {
                return ResourceManager.GetString("Entity_UndoInvokeWhileSubmitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modification of an EntityCollection whose source is external is not permitted. 的本地化字符串。
        /// </summary>
        internal static string EntityCollection_ModificationNotAllowedForExternalReference {
            get {
                return ResourceManager.GetString("EntityCollection_ModificationNotAllowedForExternalReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resolve cannot be called for delete conflicts. 的本地化字符串。
        /// </summary>
        internal static string EntityConflict_CannotResolveDeleteConflict {
            get {
                return ResourceManager.GetString("EntityConflict_CannotResolveDeleteConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PropertyNames are not available for delete conflicts. 的本地化字符串。
        /// </summary>
        internal static string EntityConflict_IsDeleteConflict {
            get {
                return ResourceManager.GetString("EntityConflict_IsDeleteConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot retrieve an EntitySet for the derived entity type &apos;{0}&apos;. Use EntityContainer.GetEntitySet(Type) to get the EntitySet for the base entity type &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string EntityContainer_CannotRetrieveEntitySetForDerivedEntity {
            get {
                return ResourceManager.GetString("EntityContainer_CannotRetrieveEntitySetForDerivedEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entity &apos;{0}&apos; cannot be attached to this EntityContainer because it is already attached to another EntityContainer. 的本地化字符串。
        /// </summary>
        internal static string EntityContainer_CrossContainerAttach {
            get {
                return ResourceManager.GetString("EntityContainer_CrossContainerAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The EntitySet for Entity &apos;{0}&apos; already exists in the EntityContainer. 的本地化字符串。
        /// </summary>
        internal static string EntityContainer_EntitySetAlreadyExists {
            get {
                return ResourceManager.GetString("EntityContainer_EntitySetAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This EntityContainer does not contain an EntitySet of type &apos;{0}&apos;. If the type is external to this EntityContainer, please make sure you’ve called AddReference to establish the external link. 的本地化字符串。
        /// </summary>
        internal static string EntityContainerDoesntContainEntityType {
            get {
                return ResourceManager.GetString("EntityContainerDoesntContainEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An EntityKey value cannot be null 的本地化字符串。
        /// </summary>
        internal static string EntityKey_CannotBeNull {
            get {
                return ResourceManager.GetString("EntityKey_CannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To create an EntityKey, you must specify at least one key value. 的本地化字符串。
        /// </summary>
        internal static string EntityKey_EmptyKeyMembers {
            get {
                return ResourceManager.GetString("EntityKey_EmptyKeyMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entity &apos;{0}&apos; cannot be added to cache because it doesn&apos;t have a valid identity. 的本地化字符串。
        /// </summary>
        internal static string EntityKey_NullIdentity {
            get {
                return ResourceManager.GetString("EntityKey_NullIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EntityQuery for Type &apos;{0}&apos; targeting query operation &apos;{1}&apos; does not support query composition. 的本地化字符串。
        /// </summary>
        internal static string EntityQuery_NotComposable {
            get {
                return ResourceManager.GetString("EntityQuery_NotComposable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An entity with the same identity already exists in this EntitySet. 的本地化字符串。
        /// </summary>
        internal static string EntitySet_DuplicateIdentity {
            get {
                return ResourceManager.GetString("EntitySet_DuplicateIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The entity being added is already attached. 的本地化字符串。
        /// </summary>
        internal static string EntitySet_EntityAlreadyAttached {
            get {
                return ResourceManager.GetString("EntitySet_EntityAlreadyAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified entity is already contained in an EntitySet 的本地化字符串。
        /// </summary>
        internal static string EntitySet_EntityAlreadyInSet {
            get {
                return ResourceManager.GetString("EntitySet_EntityAlreadyInSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified entity is not contained in this EntitySet. 的本地化字符串。
        /// </summary>
        internal static string EntitySet_EntityNotInSet {
            get {
                return ResourceManager.GetString("EntitySet_EntityNotInSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This EntitySet of Type &apos;{0}&apos; does not support the &apos;{1}&apos; operation. 的本地化字符串。
        /// </summary>
        internal static string EntitySet_UnsupportedOperation {
            get {
                return ResourceManager.GetString("EntitySet_UnsupportedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EntitySet of Type &apos;{0}&apos; cannot contain instances of Type &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string EntitySet_Wrong_Type {
            get {
                return ResourceManager.GetString("EntitySet_Wrong_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; is not supported. 的本地化字符串。
        /// </summary>
        internal static string IsNotSupported {
            get {
                return ResourceManager.GetString("IsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The operation must have been sucessfully completed 的本地化字符串。
        /// </summary>
        internal static string LoadResult_OperationNotSucessfullyCompleted {
            get {
                return ResourceManager.GetString("LoadResult_OperationNotSucessfullyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Member &apos;{0}&apos; must be marked with AssociationAttribute 的本地化字符串。
        /// </summary>
        internal static string MemberMustBeAssociation {
            get {
                return ResourceManager.GetString("MemberMustBeAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; must be an Entity. 的本地化字符串。
        /// </summary>
        internal static string MustBeAnEntity {
            get {
                return ResourceManager.GetString("MustBeAnEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MarkErrorAsHandled can only be called if HasError is true. 的本地化字符串。
        /// </summary>
        internal static string Operation_HasErrorMustBeTrue {
            get {
                return ResourceManager.GetString("Operation_HasErrorMustBeTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameter &apos;{0}&apos; cannot be null or empty. 的本地化字符串。
        /// </summary>
        internal static string Parameter_NullOrEmpty {
            get {
                return ResourceManager.GetString("Parameter_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type &apos;{0}&apos; does not contain a public property named &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Property_Does_Not_Exist {
            get {
                return ResourceManager.GetString("Property_Does_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The &apos;{0}&apos; property is read only. 的本地化字符串。
        /// </summary>
        internal static string Property_Is_ReadOnly {
            get {
                return ResourceManager.GetString("Property_Is_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type &apos;{0}&apos; does not derive from Entity 的本地化字符串。
        /// </summary>
        internal static string Type_Not_Entity {
            get {
                return ResourceManager.GetString("Type_Not_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ambiguous match for method &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ValidationUtilities_AmbiguousMatch {
            get {
                return ResourceManager.GetString("ValidationUtilities_AmbiguousMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ValidationContext.ObjectInstance cannot be null. 的本地化字符串。
        /// </summary>
        internal static string ValidationUtilities_ContextInstance_CannotBeNull {
            get {
                return ResourceManager.GetString("ValidationUtilities_ContextInstance_CannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method &apos;{0}.{1}({3})&apos; could not be found. Parameter count: {2}. 的本地化字符串。
        /// </summary>
        internal static string ValidationUtilities_MethodNotFound {
            get {
                return ResourceManager.GetString("ValidationUtilities_MethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method &apos;{0}.{1}&apos; accepting zero parameters could not be found. 的本地化字符串。
        /// </summary>
        internal static string ValidationUtilities_MethodNotFound_ZeroParams {
            get {
                return ResourceManager.GetString("ValidationUtilities_MethodNotFound_ZeroParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation &apos;{0}&apos; does not exist. 的本地化字符串。
        /// </summary>
        internal static string WebDomainClient_OperationDoesNotExist {
            get {
                return ResourceManager.GetString("WebDomainClient_OperationDoesNotExist", resourceCulture);
            }
        }
    }
}
