//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRiaServices.DomainServices.Client {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRiaServices.DomainServices.Client.Web.Data.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The current application or application host is null and the host URI cannot be determined. 的本地化字符串。
        /// </summary>
        internal static string DomainClient_UnableToDetermineHostUri {
            get {
                return ResourceManager.GetString("DomainClient_UnableToDetermineHostUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified service URI is not correctly formatted. 的本地化字符串。
        /// </summary>
        internal static string DomainContext_InvalidServiceUri {
            get {
                return ResourceManager.GetString("DomainContext_InvalidServiceUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load operation failed for query &apos;{0}&apos;. {1} 的本地化字符串。
        /// </summary>
        internal static string DomainContext_LoadOperationFailed {
            get {
                return ResourceManager.GetString("DomainContext_LoadOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit operation failed. {0} 的本地化字符串。
        /// </summary>
        internal static string DomainContext_SubmitOperationFailed {
            get {
                return ResourceManager.GetString("DomainContext_SubmitOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The PoxBinaryMessageEncoder only supports content type {0}. 的本地化字符串。
        /// </summary>
        internal static string PoxBinaryMessageEncoder_InvalidContentType {
            get {
                return ResourceManager.GetString("PoxBinaryMessageEncoder_InvalidContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The message has MessageVersion {0} but the encoder is configured for MessageVersion {1}. 的本地化字符串。
        /// </summary>
        internal static string PoxBinaryMessageEncoder_InvalidMessageVersion {
            get {
                return ResourceManager.GetString("PoxBinaryMessageEncoder_InvalidMessageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The PoxBinaryMessageEncoder only supports MessageVersion.None. 的本地化字符串。
        /// </summary>
        internal static string PoxBinaryMessageEncoder_MessageVersionNotSupported {
            get {
                return ResourceManager.GetString("PoxBinaryMessageEncoder_MessageVersionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The maximum URI length of {0} was exceeded. 的本地化字符串。
        /// </summary>
        internal static string WebDomainClient_MaximumUriLengthExceeded {
            get {
                return ResourceManager.GetString("WebDomainClient_MaximumUriLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation &apos;{0}&apos; does not exist. 的本地化字符串。
        /// </summary>
        internal static string WebDomainClient_OperationDoesNotExist {
            get {
                return ResourceManager.GetString("WebDomainClient_OperationDoesNotExist", resourceCulture);
            }
        }
    }
}
